using RobotJack.Common.Titan;

namespace RobotJack.Content.Abilities
{
	// Generated by tools/titan_abilities.py: the Shift Titan's nine abilities for each fusion (see TitanAbilities.cs).

	// Shift Titan (no trigger merged)
	public class ShiftArm : TitanArm { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftAura : TitanAura { public override TitanFusion Fusion => TitanFusion.None; }
	public class ShiftOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.None; }

	// Plasma Titan (Robot Trigger merged)
	public class PlasmaArm : TitanArm { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaAura : TitanAura { public override TitanFusion Fusion => TitanFusion.Robot; }
	public class PlasmaOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.Robot; }

	// Inferno Titan (Blaze Trigger merged)
	public class InfernoArm : TitanArm { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoAura : TitanAura { public override TitanFusion Fusion => TitanFusion.Blaze; }
	public class InfernoOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.Blaze; }

	// Glacier Titan (Frost Trigger merged)
	public class GlacierArm : TitanArm { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierAura : TitanAura { public override TitanFusion Fusion => TitanFusion.Frost; }
	public class GlacierOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.Frost; }

	// Storm Titan (Volt Trigger merged)
	public class StormArm : TitanArm { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormAura : TitanAura { public override TitanFusion Fusion => TitanFusion.Volt; }
	public class StormOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.Volt; }

	// Void Titan (Shadow Trigger merged)
	public class VoidArm : TitanArm { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidAura : TitanAura { public override TitanFusion Fusion => TitanFusion.Shadow; }
	public class VoidOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.Shadow; }

	// Star Titan (Nova Trigger merged)
	public class StarArm : TitanArm { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarAura : TitanAura { public override TitanFusion Fusion => TitanFusion.Nova; }
	public class StarOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.Nova; }

	// Omega Titan (Omega Trigger merged)
	public class OmegaArm : TitanArm { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaAura : TitanAura { public override TitanFusion Fusion => TitanFusion.Omega; }
	public class OmegaOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.Omega; }

	// Divine Titan (God Trigger merged)
	public class DivineArm : TitanArm { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineCoreBeam : TitanCoreBeam { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineStomp : TitanStomp { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineEruption : TitanEruption { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineSkyfall : TitanSkyfall { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineMissilePods : TitanMissiles { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineSatellites : TitanSatellites { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineAura : TitanAura { public override TitanFusion Fusion => TitanFusion.God; }
	public class DivineOverdrive : TitanOverdrive { public override TitanFusion Fusion => TitanFusion.God; }
}
