"""Generates the Shift Titan's 81 ability classes (Content/Abilities/TitanAbilityList.cs): nine abilities for each of the
nine fusions. Also used by generate_titan_sprites.py for the icons and to print the localization entries.
Run from the repository root: python3 tools/titan_abilities.py"""

# fusion -> (name prefix, element, words for the element in tooltips)
FUSIONS = {
    "None": ("Shift", "Tech", "tech energy"),
    "Robot": ("Plasma", "Plasma", "plasma"),
    "Blaze": ("Inferno", "Blaze", "fire"),
    "Frost": ("Glacier", "Frost", "ice"),
    "Volt": ("Storm", "Volt", "lightning"),
    "Shadow": ("Void", "Shadow", "void"),
    "Nova": ("Star", "Nova", "starlight"),
    "Omega": ("Omega", "Prism", "prismatic energy"),
    "God": ("Divine", "Holy", "holy light"),
}

# kind -> (base class, class/display suffix, tooltip)
KINDS = [
    ("TitanArm", "Arm", "Arm", "Attack with the titan's weapon arm, chosen in the Shift Trigger's menu:\n"
     "Cannon: three huge {el} bolts\nBlade: a huge sweeping slash\nClaw: three raking slashes, a little weaker"),
    ("TitanCoreBeam", "CoreBeam", "Core Beam", "Hold left click to fire a giant beam of {el} out of the titan's core\nCuts through blocks"),
    ("TitanStomp", "Stomp", "Stomp", "Stomp the ground: a shockwave of {el} bursts out from your feet\nand the ground erupts on both sides"),
    ("TitanEruption", "Eruption", "Eruption", "Eleven giant pillars of {el} burst out of the ground across the cursor"),
    ("TitanSkyfall", "Skyfall", "Skyfall", "Twenty huge exploding bolts of {el} rain down from the sky onto the cursor"),
    ("TitanMissiles", "MissilePods", "Missile Pods", "Launch sixteen homing {el} missiles from the titan's backpack"),
    ("TitanSatellites", "Satellites", "Satellites", "Six orbs of {el} split off your core and circle the titan for 10 seconds"),
    ("TitanAura", "Aura", "Aura", "Surround the whole titan with {el} for 8 seconds, hurting everything inside"),
    ("TitanOverdrive", "Overdrive", "Overdrive", "Overload your core: an enormous blast of {el},\nthe ground erupts all around you and bolts fly out in every direction"),
]

# Extra tooltip line for each fusion: how its bolts and blasts behave.
FUSION_PERK = {
    "None": None,
    "Robot": "Plasma Titan: bolts pierce through enemies",
    "Blaze": "Inferno Titan: bolts explode",
    "Frost": "Glacier Titan: bolts pierce, blasts freeze enemies",
    "Volt": "Storm Titan: bolts home in on enemies",
    "Shadow": "Void Titan: bolts pierce and home in",
    "Nova": "Star Titan: bolts explode and home in",
    "Omega": "Omega Titan: bolts explode, pierce and home in, blasts freeze enemies",
    "God": "Divine Titan: bolts explode, pierce and home in",
}


def abilities():
    """(class name, fusion, base class, kind suffix, display name, tooltip) for all 81 abilities."""
    out = []
    for fusion, (prefix, element, words) in FUSIONS.items():
        for base, suffix, display, tip in KINDS:
            tooltip = tip.format(el=words)
            if FUSION_PERK[fusion]:
                tooltip += "\n" + FUSION_PERK[fusion]
            out.append((prefix + suffix, fusion, base, suffix, "%s %s" % (prefix, display), tooltip))
    return out


def write_classes():
    lines = [
        "using RobotJack.Common.Titan;",
        "",
        "namespace RobotJack.Content.Abilities",
        "{",
        "\t// Generated by tools/titan_abilities.py: the Shift Titan's nine abilities for each fusion (see TitanAbilities.cs).",
    ]
    last = None
    for name, fusion, base, _suffix, _display, _tip in abilities():
        if fusion != last:
            lines.append("")
            lines.append("\t// %s (%s)" % (FUSIONS[fusion][0] + " Titan", "no trigger merged" if fusion == "None" else fusion + " Trigger merged"))
            last = fusion
        lines.append("\tpublic class %s : %s { public override TitanFusion Fusion => TitanFusion.%s; }" % (name, base, fusion))
    lines.append("}")
    with open("Content/Abilities/TitanAbilityList.cs", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote Content/Abilities/TitanAbilityList.cs")


def hjson_items():
    out = []
    for name, _fusion, _base, _suffix, display, tip in abilities():
        out.append("\t\t\t%s: {" % name)
        out.append("\t\t\t\tDisplayName: %s" % display)
        out.append("\t\t\t\tTooltip:")
        out.append("\t\t\t\t\t'''")
        for line in tip.split("\n"):
            out.append("\t\t\t\t\t" + line)
        out.append("\t\t\t\t\t'''")
        out.append("\t\t\t}")
        out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    write_classes()
